---
name: Portfolio Nakor Rider CI

on: 
  push:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Super-Linter (skip StandardJS)
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_STANDARD: false    # Skip StandardJS linting
          VALIDATE_JSCPD: true        # Keep duplicate code detection
          VALIDATE_HTML: true         # Keep HTML linting enabled
          VALIDATE_CSS: true          # Keep CSS linting enabled
          # Add more VALIDATE_* if you want to enable/disable other linters

      - name: Check for Broken Links
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          timeout: 30
          concurrency: 5
