---
name: Portfolio Nakor Rider CI

on: 
  push:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run HTML Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JSCPD_THRESHOLD: 5

      - name: Check for Broken Links
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          # Optional: add ignore or config options here

