---
name: Portfolio Nakor Rider CI

on: 
  push:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Super-Linter (skip StandardJS, JSCPD, CSS, HTML)
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_STANDARD: false
          VALIDATE_JSCPD: false
          VALIDATE_CSS: false
          VALIDATE_HTML: false

      - name: Check for Broken Links
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          timeout: 30
          concurrency: 5
