---
name: Portfolio Nakor Rider CI

on: 
  push:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Super-Linter (allow errors)
        uses: github/super-linter@v4
        continue-on-error: true   # THIS MAKES THE STEP NOT FAIL THE JOB
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_STANDARD: false
          VALIDATE_JSCPD: false
          VALIDATE_CSS: false
          VALIDATE_HTML: false
          VALIDATE_MARKDOWN: false
          VALIDATE_YAML: false
          VALIDATE_JSON: false
          VALIDATE_PYTHON: false
          VALIDATE_BASH: false
          VALIDATE_DOCKERFILE: false

      - name: Check for Broken Links
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          timeout: 30
          concurrency: 5

