---
name: Portfolio Nakor Rider CI

on: 
  push:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run HTML Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JSCPD: false       # Disable duplicate code check for now
          VALIDATE_STANDARD: false    # Disable JavaScript Standard Style check for now
          JSCPD_THRESHOLD: 5          # Just in case (ignored with VALIDATE_JSCPD:false)

      - name: Check for Broken Links
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          timeout: 30                # Timeout per request in seconds
          concurrency: 5             # Limit concurrent requests
